BeebDB/Controllers/BeebGamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeebDB;
using PagedList;

namespace BeebDB.Controllers
{
  public class BeebGamesController : Controller
  {
    private beebdbEntities db = new beebdbEntities();

    // GET: BeebGames
    public ActionResult Index()
    {
      return View(db.beebgames.ToList());
    }

    // GET: BeebGames/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }

      beebgame beebgame = db.beebgames.Find(id);

      if (beebgame == null)
      {
        return HttpNotFound();
      }

      return View(beebgame);
    }

    // GET: BeebGames/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: BeebGames/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "game_id,title,year,developer,publisher,genre")] beebgame beebgame)
    {
      if (ModelState.IsValid)
      {
        db.beebgames.Add(beebgame);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(beebgame);
    }

    // GET: BeebGames/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null)
      {
          return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }

      beebgame beebgame = db.beebgames.Find(id);

      if (beebgame == null)
      {
          return HttpNotFound();
      }
      return View(beebgame);
    }

    // POST: BeebGames/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "game_id,title,year,developer,publisher,genre,screenshotmain,screenshotalt")] beebgame beebgame)
    {
      if (ModelState.IsValid)
      {
          db.Entry(beebgame).State = EntityState.Modified;
          db.SaveChanges();
          return RedirectToAction("Index");
      }

      return View(beebgame);
    }

    // GET: BeebGames/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
          return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      beebgame beebgame = db.beebgames.Find(id);
      if (beebgame == null)
      {
          return HttpNotFound();
      }

      return View(beebgame);
    }

    // POST: BeebGames/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      beebgame beebgame = db.beebgames.Find(id);
      db.beebgames.Remove(beebgame);
      db.SaveChanges();

      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
          db.Dispose();
      }

      base.Dispose(disposing);
    }
  }
}

BeebDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "BeebGames", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("The DB", "Index", "BeebGames")</li>
                    <li>@Html.ActionLink("News", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/listjs")
    @RenderSection("scripts", required: false)
</body>
</html>